package co.edu.icesi.demobanco.modelo;
// Generated 21/05/2018 03:27:45 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransferenciasId generated by hbm2java
 */
@Embeddable
public class TransferenciasId implements java.io.Serializable {

	private long tranCodigo;
	private String cueNumeroOrigen;
	private String cueNumeroDestino;

	public TransferenciasId() {
	}

	public TransferenciasId(long tranCodigo, String cueNumeroOrigen, String cueNumeroDestino) {
		this.tranCodigo = tranCodigo;
		this.cueNumeroOrigen = cueNumeroOrigen;
		this.cueNumeroDestino = cueNumeroDestino;
	}

	@Column(name = "tran_codigo", nullable = false, precision = 10, scale = 0)
	public long getTranCodigo() {
		return this.tranCodigo;
	}

	public void setTranCodigo(long tranCodigo) {
		this.tranCodigo = tranCodigo;
	}

	@Column(name = "cue_numero_origen", nullable = false, length = 30)
	public String getCueNumeroOrigen() {
		return this.cueNumeroOrigen;
	}

	public void setCueNumeroOrigen(String cueNumeroOrigen) {
		this.cueNumeroOrigen = cueNumeroOrigen;
	}

	@Column(name = "cue_numero_destino", nullable = false, length = 30)
	public String getCueNumeroDestino() {
		return this.cueNumeroDestino;
	}

	public void setCueNumeroDestino(String cueNumeroDestino) {
		this.cueNumeroDestino = cueNumeroDestino;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransferenciasId))
			return false;
		TransferenciasId castOther = (TransferenciasId) other;

		return (this.getTranCodigo() == castOther.getTranCodigo())
				&& ((this.getCueNumeroOrigen() == castOther.getCueNumeroOrigen())
						|| (this.getCueNumeroOrigen() != null && castOther.getCueNumeroOrigen() != null
								&& this.getCueNumeroOrigen().equals(castOther.getCueNumeroOrigen())))
				&& ((this.getCueNumeroDestino() == castOther.getCueNumeroDestino())
						|| (this.getCueNumeroDestino() != null && castOther.getCueNumeroDestino() != null
								&& this.getCueNumeroDestino().equals(castOther.getCueNumeroDestino())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTranCodigo();
		result = 37 * result + (getCueNumeroOrigen() == null ? 0 : this.getCueNumeroOrigen().hashCode());
		result = 37 * result + (getCueNumeroDestino() == null ? 0 : this.getCueNumeroDestino().hashCode());
		return result;
	}

}
