package co.edu.icesi.demobanco.modelo;
// Generated 21/05/2018 03:27:45 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transferencias generated by hbm2java
 */
@Entity
@Table(name = "transferencias", schema = "public")
public class Transferencias implements java.io.Serializable {

	private TransferenciasId id;
	private Clientes clientes;
	private Cuentas cuentasByCueNumeroDestino;
	private Cuentas cuentasByCueNumeroOrigen;
	private Usuarios usuarios;
	private BigDecimal tranValor;
	private Date tranFecha;
	private String tranDescripcion;

	public Transferencias() {
	}

	public Transferencias(TransferenciasId id, Clientes clientes, Cuentas cuentasByCueNumeroDestino,
			Cuentas cuentasByCueNumeroOrigen, Usuarios usuarios, BigDecimal tranValor, Date tranFecha,
			String tranDescripcion) {
		this.id = id;
		this.clientes = clientes;
		this.cuentasByCueNumeroDestino = cuentasByCueNumeroDestino;
		this.cuentasByCueNumeroOrigen = cuentasByCueNumeroOrigen;
		this.usuarios = usuarios;
		this.tranValor = tranValor;
		this.tranFecha = tranFecha;
		this.tranDescripcion = tranDescripcion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tranCodigo", column = @Column(name = "tran_codigo", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "cueNumeroOrigen", column = @Column(name = "cue_numero_origen", nullable = false, length = 30)),
			@AttributeOverride(name = "cueNumeroDestino", column = @Column(name = "cue_numero_destino", nullable = false, length = 30)) })
	public TransferenciasId getId() {
		return this.id;
	}

	public void setId(TransferenciasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cli_id", nullable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cue_numero_destino", nullable = false, insertable = false, updatable = false)
	public Cuentas getCuentasByCueNumeroDestino() {
		return this.cuentasByCueNumeroDestino;
	}

	public void setCuentasByCueNumeroDestino(Cuentas cuentasByCueNumeroDestino) {
		this.cuentasByCueNumeroDestino = cuentasByCueNumeroDestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cue_numero_origen", nullable = false, insertable = false, updatable = false)
	public Cuentas getCuentasByCueNumeroOrigen() {
		return this.cuentasByCueNumeroOrigen;
	}

	public void setCuentasByCueNumeroOrigen(Cuentas cuentasByCueNumeroOrigen) {
		this.cuentasByCueNumeroOrigen = cuentasByCueNumeroOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usu_cedula", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "tran_valor", nullable = false, precision = 10)
	public BigDecimal getTranValor() {
		return this.tranValor;
	}

	public void setTranValor(BigDecimal tranValor) {
		this.tranValor = tranValor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tran_fecha", nullable = false, length = 29)
	public Date getTranFecha() {
		return this.tranFecha;
	}

	public void setTranFecha(Date tranFecha) {
		this.tranFecha = tranFecha;
	}

	@Column(name = "tran_descripcion", nullable = false, length = 50)
	public String getTranDescripcion() {
		return this.tranDescripcion;
	}

	public void setTranDescripcion(String tranDescripcion) {
		this.tranDescripcion = tranDescripcion;
	}

}
